// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as library$0 from "../../../../Ricori/finoka/desktop/internal/library/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "files:dropped": string[] | null;
            "library:changed": library$0.Entry[] | null;
        }
    }
}
