// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService coordinates the home and editor windows. The editor owns its
 * unsaved-change UI; native close requests are forwarded to it and only
 * CloseEditor is allowed to destroy the window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * CloseEditor is called only after the editor has resolved its unsaved state.
 */
export function CloseEditor(): $CancellablePromise<void> {
    return $Call.ByID(2775320491);
}

export function OpenEditor(id: string): $CancellablePromise<void> {
    return $Call.ByID(2785033743, id);
}
