// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sidecar$0 from "../sidecar/models.js";

/**
 * CancelRuntimeInstall stops the running provisioning job. The sidecar cancels
 * cooperatively and keeps whatever it already downloaded, so this is a stop
 * rather than a rollback.
 */
export function CancelRuntimeInstall(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2224560352);
}

export function CancelTask(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3714944418, taskID);
}

export function Capabilities(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(503721799);
}

export function Document(videoID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1586406156, videoID);
}

export function DocumentPeaks(videoID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1291765324, videoID);
}

/**
 * ImportDocument turns a finished subtitle axis into an editable document
 * without running a task: a bilingual or translated file has nothing left for
 * the engine to compute.
 */
export function ImportDocument(payload: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(594730557, payload);
}

export function InstallPython(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1411586738);
}

export function InstallRuntime(target: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3997580972, target);
}

export function ListTasks(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(927138817);
}

export function PythonBootstrapStatus(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3430045125);
}

/**
 * RemoveRuntime removes replaceable managed environments and caches. The
 * sidecar preserves tasks, subtitle documents, and user settings.
 */
export function RemoveRuntime(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2762506059);
}

/**
 * RemoveRuntimeGroup removes one managed optional-tool group without touching
 * the required runtime, models, tasks, subtitles, or user settings.
 */
export function RemoveRuntimeGroup(target: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3318269218, target);
}

export function ResumeTask(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1056607311, taskID);
}

export function RetryTask(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2132432784, taskID);
}

export function RuntimeProvisionStatus(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(772810948);
}

export function SaveDocument(videoID: string, document: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1464586905, videoID, document);
}

export function SaveKeys(keys: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2193389684, keys);
}

/**
 * SetDocumentAxis records the imported subtitle axis a run on this video must
 * land on, or clears it when axis is nil. It is stored beside the document
 * rather than carried in the TaskRequest because the projection consumes it,
 * and a cloud task's artifacts are projected locally without its request ever
 * reaching the sidecar.
 */
export function SetDocumentAxis(videoID: string, axis: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(422148627, videoID, axis);
}

export function Settings(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(4011041744);
}

export function SidecarStatus(): $CancellablePromise<sidecar$0.Snapshot> {
    return $Call.ByID(3363346858);
}

export function StartTask(request: { [_ in string]?: any } | null): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(317097246, request);
}

export function TaskArtifacts(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2801091719, taskID);
}

export function TaskEvents(taskID: string, afterCursor: number): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1930233789, taskID, afterCursor);
}

export function TaskStatus(taskID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3900097390, taskID);
}
