// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Snapshot is safe to expose to the renderer. The session token is
 * intentionally absent; authenticated calls stay inside Manager.DoJSON.
 */
export interface Snapshot {
    "running": boolean;
    "baseUrl"?: string;
    "pid"?: number;
    "error"?: string;
}
