// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Change {
    "kind": string;
    "pluginId": string;
}

export interface Contributions {
    "tools": ToolContribution[] | null;
}

export interface DownloadedMedia {
    "platform": string;
    "outputPath": string;
    "media": MediaSummary;
}

export interface ExportedArtifact {
    "path": string;
    "format": string;
    "size": number;
}

export interface InstalledPlugin {
    "id": string;
    "name": string;
    "version": string;
    "apiVersion": number;
    "description"?: string;
    "publisher"?: string;
    "license"?: string;
    "permissions"?: string[] | null;
    "contributes": Contributions;
    "enabled": boolean;
}

export interface MediaSummary {
    "id": string;
    "title": string;
    "duration": number;
    "width": number;
    "height": number;
    "available": boolean;
    "documentAvailable": boolean;
}

export interface ToolContribution {
    "id": string;
    "title": string;
    "icon"?: string;
    "page": string;
    "order"?: number;
}
