// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportAudio is a structured FFmpeg capability. Plugins select a Finoka media
 * ID and an output format; the host owns input resolution, arguments, the save
 * dialog, temporary files, and final publication.
 */
export function ExportAudio(pluginID: string, mediaID: string, format: string): $CancellablePromise<$models.ExportedArtifact> {
    return $Call.ByID(2716183520, pluginID, mediaID, format);
}

/**
 * Install accepts a .finoka-plugin ZIP or an unpacked plugin directory. The
 * directory form is intended for developer workflows and automated tests.
 */
export function Install(path: string): $CancellablePromise<$models.InstalledPlugin> {
    return $Call.ByID(4213420995, path);
}

export function List(): $CancellablePromise<$models.InstalledPlugin[] | null> {
    return $Call.ByID(100861768);
}

export function MediaList(pluginID: string): $CancellablePromise<$models.MediaSummary[] | null> {
    return $Call.ByID(3561990828, pluginID);
}

export function PageHTML(pluginID: string, toolID: string): $CancellablePromise<string> {
    return $Call.ByID(1769821126, pluginID, toolID);
}

export function PickAndInstall(): $CancellablePromise<$models.InstalledPlugin> {
    return $Call.ByID(787520081);
}

/**
 * RunYTDLP executes plugin-supplied yt-dlp arguments from a closed safe set for
 * public YouTube and Twitch URLs. The host still owns tool resolution, the
 * output path, FFmpeg wiring and the final media-library import.
 */
export function RunYTDLP(pluginID: string, rawURL: string, pluginArgs: string[] | null): $CancellablePromise<$models.DownloadedMedia> {
    return $Call.ByID(2793227616, pluginID, rawURL, pluginArgs);
}

export function SetEnabled(id: string, enabled: boolean): $CancellablePromise<$models.InstalledPlugin> {
    return $Call.ByID(779905873, id, enabled);
}

export function Uninstall(id: string, removeData: boolean): $CancellablePromise<void> {
    return $Call.ByID(2590740258, id, removeData);
}
