// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConsumeReleaseNotes returns the notes for the running build exactly once.
 */
export function ConsumeReleaseNotes(): $CancellablePromise<$models.ReleaseNotes | null> {
    return $Call.ByID(3227564453);
}

/**
 * CurrentVersion is the running build, shown in the UI next to the update button.
 */
export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(4230214776);
}

/**
 * GetStatus reports the current download lifecycle to the renderer.
 */
export function GetStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(1062049407);
}

/**
 * InstallUpdate swaps in the staged build and restarts. It reports false when
 * nothing is staged or the restart could not be handed off.
 */
export function InstallUpdate(): $CancellablePromise<boolean> {
    return $Call.ByID(1280722867);
}
