// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Get(): $CancellablePromise<$models.State> {
    return $Call.ByID(1639680122);
}

export function GetWindowBounds(kind: string): $CancellablePromise<[$models.WindowBounds, boolean]> {
    return $Call.ByID(1826137015, kind);
}

export function Save(patch: { [_ in string]?: any } | null): $CancellablePromise<$models.State> {
    return $Call.ByID(2908468395, patch);
}

export function SetWindowBounds(kind: string, bounds: $models.WindowBounds): $CancellablePromise<void> {
    return $Call.ByID(2378971099, kind, bounds);
}
