// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StorageService moves Finoka's two large directories to another drive.
 * 
 * The move is the easy half; the hard half is that the FineSub install root is
 * in use by a running sidecar whose Python interpreter lives inside it. So a
 * runtime relocation stops the sidecar, moves, records, and starts it again
 * against a freshly resolved configuration — the same sequence the managed
 * Python installer already uses to swap interpreters.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelRelocation stops a move in progress. The partial copy is removed and
 * the source is left exactly as it was.
 */
export function CancelRelocation(): $CancellablePromise<$models.RelocationProgress> {
    return $Call.ByID(3057458980);
}

/**
 * ChooseDirectory opens the folder picker and resolves what the pick means: the
 * exact directory Finoka would own, whether it is on the same volume (a move
 * that costs nothing) and whether the volume has room.
 */
export function ChooseDirectory(target: string): $CancellablePromise<$models.Destination> {
    return $Call.ByID(3820186576, target);
}

export function Progress(): $CancellablePromise<$models.RelocationProgress> {
    return $Call.ByID(1666096887);
}

/**
 * Refresh re-measures both directories and reports the result. Status caches
 * sizes for measurementTTL, which is right for repeated renders and wrong right
 * after an install has just written several gigabytes: the install page decides
 * whether to keep offering a location change from these numbers.
 */
export function Refresh(): $CancellablePromise<$models.StorageStatus> {
    return $Call.ByID(1782226567);
}

/**
 * Relocate moves target to destination and records the new location. It returns
 * as soon as the move has started; progress arrives on storage:progress.
 */
export function Relocate(target: string, destination: string): $CancellablePromise<$models.RelocationProgress> {
    return $Call.ByID(2789513399, target, destination);
}

/**
 * ResetLocation moves target back under the Finoka data directory.
 */
export function ResetLocation(target: string): $CancellablePromise<$models.RelocationProgress> {
    return $Call.ByID(1329736460, target);
}

/**
 * Status reports both directories and any move in flight.
 */
export function Status(): $CancellablePromise<$models.StorageStatus> {
    return $Call.ByID(141110822);
}
