// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AdminKey {
    "id": string;
    "name": string;
    "key": string;
    "keyPreview": string;
    "remaining": number;
    "submitted"?: number;
    "running"?: number;
    "createdAt"?: string;
}

export interface Entry {
    "id": string;
    "title": string;
    "fingerprint": string;
    "duration": number;
    "status": string;
    "source": string;

    /**
     * Reported by whichever desktop put the cover there, not probed by the
     * backend: a cloud task PUTs it to a presigned slot the backend never sees
     * the body of, and a local run sends it with the subtitles it syncs. False
     * wherever neither could produce one -- a source with no video stream, or a
     * machine without ffmpeg -- and the library then asks for no frame at all.
     */
    "thumbnailAvailable"?: boolean;

    /**
     * Which subtitle artifacts the entry holds, written by whichever run last
     * published a set. Status describes the newest attempt; this describes what
     * is actually retrievable, and the two come apart whenever a re-transcribe
     * of the same media is queued, running, or has failed -- the backend reuses
     * the library id for those, and the previous run's files stay in place until
     * a completing run replaces them.
     */
    "artifactNames"?: string[] | null;
    "engineCommit"?: string;
    "createdAt": string;
    "updatedAt": string;
    "ownerId"?: string;
    "ownerName"?: string;
}

export interface IssuedAdminKey {
    "id": string;
    "name": string;
    "keyPreview": string;
    "remaining": number;
    "submitted"?: number;
    "running"?: number;
    "createdAt"?: string;
    "key": string;
    "generated": boolean;
}

export interface Session {
    "authenticated": boolean;
    "backend"?: string;
    "admin"?: boolean;
    "name"?: string;
    "remaining"?: number | null;
    "running": number;
    "synced"?: number;
    "syncSkipped"?: number;
    "syncFailed"?: number;
    "cloudVideos"?: number;
    "syncError"?: string;
}
