// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AdminKey {
    "id": string;
    "name": string;
    "key": string;
    "keyPreview": string;
    "remaining": number;
    "submitted"?: number;
    "running"?: number;
    "createdAt"?: string;
}

export interface Entry {
    "id": string;
    "title": string;
    "fingerprint": string;
    "duration": number;
    "status": string;
    "source": string;

    /**
     * Reported by whichever desktop started the task, not probed by the
     * backend. False for entries synced from a local run: those never went
     * through an upload, so the bucket has no frame for them.
     */
    "thumbnailAvailable"?: boolean;
    "engineCommit"?: string;
    "createdAt": string;
    "updatedAt": string;
    "ownerId"?: string;
    "ownerName"?: string;
}

export interface IssuedAdminKey {
    "id": string;
    "name": string;
    "keyPreview": string;
    "remaining": number;
    "submitted"?: number;
    "running"?: number;
    "createdAt"?: string;
    "key": string;
    "generated": boolean;
}

export interface Session {
    "authenticated": boolean;
    "backend"?: string;
    "admin"?: boolean;
    "name"?: string;
    "remaining"?: number | null;
    "running": number;
    "synced"?: number;
    "syncSkipped"?: number;
    "syncFailed"?: number;
    "cloudVideos"?: number;
    "syncError"?: string;
}
