// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReleaseNotes is handed to the renderer once, on the first launch after an
 * update installed successfully.
 */
export interface ReleaseNotes {
    "version": string;
    "notes": string;
}

/**
 * Status mirrors the download lifecycle for the renderer. Stage is one of
 * idle, checking, download, verify, unpack, ready, waiting-editor, installing
 * or retry.
 */
export interface Status {
    "mandatory": boolean;
    "version": string;
    "stage": string;
    "done": number;
    "total": number;
    "ready": boolean;
}
