// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConsumeReleaseNotes returns the notes for the running build exactly once.
 */
export function ConsumeReleaseNotes(): $CancellablePromise<$models.ReleaseNotes | null> {
    return $Call.ByID(2920710358);
}

/**
 * CurrentVersion is the running build, shown in the UI next to the update button.
 */
export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(2826856549);
}

/**
 * GetStatus reports the current download lifecycle to the renderer.
 */
export function GetStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(2753174248);
}

/**
 * InstallUpdate swaps in the staged build and restarts. It reports false when
 * nothing is staged or the restart could not be handed off.
 */
export function InstallUpdate(): $CancellablePromise<boolean> {
    return $Call.ByID(867706792);
}
